### ISSUE TITLE
Built failed

### ISSUE THREAD

**Issue by trancept** [ethz-asl/nbvplanner#1]
Hello,
Thanks for sharing this project !

Compilation with catkin_make on ROS Indigo end up with an error.
[...]
[100%] Built target gflags_nothreads-shared
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags.so.2.2.0
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags.so.2
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags.so
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags_nothreads.so.2.2.0
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags_nothreads.so.2
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/libgflags_nothreads.so
-- Installing: /opt/nrx/ros/ethz-asl/devel/include/gflags/gflags.h
-- Installing: /opt/nrx/ros/ethz-asl/devel/include/gflags/gflags_declare.h
-- Installing: /opt/nrx/ros/ethz-asl/devel/include/gflags/gflags_completions.h
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/cmake/gflags/gflags-config.cmake
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/cmake/gflags/gflags-config-version.cmake
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/cmake/gflags/gflags-export.cmake
-- Installing: /opt/nrx/ros/ethz-asl/devel/lib/cmake/gflags/gflags-export-release.cmake
-- Installing: /opt/nrx/ros/ethz-asl/devel/bin/gflags_completions.sh
[ 23%] Completed 'gflags_src'
[ 23%] Built target gflags_src
make: *** [all] Error 2
**Invoking "make -j8 -l8" failed**

Full log in attachement.
[build-log.txt](https://github.com/ethz-asl/nbvplanner/files/124670/build-log.txt)

**Comment by birchera** [comment]
You will need to compile it using the ros-catkin-tools package and the command
```sh
catkin build
```
If you don't have it installed you can get it with
```sh
apt-get install ros-catkin-tools
```
Refer to the [installation instruction](https://github.com/ethz-asl/nbvplanner/wiki/Installation-Instructions) wiki page for more information on the installation.

Let me know if this does not work for you.

**Comment by trancept** [comment]
Thanks for updating the documentation with `sudo apt-get install python-catkin-tools`
My error was a mismatch with opencv dependencies.
Now it build.
