### ISSUE TITLE
installation fails, catkin_simple repository is not available

### ISSUE THREAD

**Issue by schrottulk** [ethz-asl/nbvplanner#13]
Hi there,
when I run this step 

> git submodule update --recursive 

from the installation instructions I get:

> remote: Repository not found.
> fatal: repository 'https://github.com/ethz-asl/catkin_simple/' not found
> Clone of 'https://github.com/ethz-asl/catkin_simple' into submodule path 'catkin_simple' failed

Furthermore accessing the catkin_simple folder results in a 404 error page. 
Thanks in advance!

**Comment by andre-nguyen** [comment]
Try this one? https://github.com/catkin/catkin_simple

**Comment by birchera** [comment]
@fmina apparently the catkin simple repo was deleted, can you advice on whether it should just work with the upstream one or if we had some custom modifications?

**Comment by fmina** [comment]
There is no need for changes. https://github.com/catkin/catkin_simple should work.

**Comment by fmina** [comment]
#14 this should fix it

**Comment by birchera** [comment]
Thanks for the quick fix Mina.

Note: If you want to update an existing clone you will need to invoke `git submodule sync` and `git submodule update` to fetch the new submodule.
