### ISSUE TITLE
fatal error: nbvplanner/nbvp_srv.h: No such file or directory

### ISSUE THREAD

**Issue by kuoshih** [ethz-asl/nbvplanner#15]
Dear all,

I tried to compile nbvplanner using catkin build. But, it failed to build nbvplanner and interface_nbvp_rotors.
In nbvp.h and exploration.cpp, they include <nbvplanner/nbvp_srv.h>.
However, there is no nbvp_srv.h file in the source code.
Do I miss something?

Thanks for any suggestions!

**Comment by birchera** [comment]
Hi @kuoshih, the file that should be included is [this](https://github.com/ethz-asl/nbvplanner/blob/master/nbvplanner/srv/nbvp_srv.srv). It is used to generate the service call. Can you verify that it is there?

It is hard to tell why this would fail for you. Did you do any adaptations or is this a fresh clone?

**Comment by kuoshih** [comment]
But, there is no header file in nbvp_srv.srv, right?

Well... my setup is as follows:
1. mmdir catkin_ws2 and move to catkin_ws2\src
2. git clone modules in catkin_ws2\src
3. copy nbvplanner folder to catkin_ws2\src since there are folders (\include, \src, srv\ ) and files.
4. catkin build in catkin_ws2 folder
5. show the mentioned error messages

I also tried not to copy  nbvplanner folder to catkin_ws2\src  (just skip step3).
Then, the same error messages shown when building interface_nbvp_rotors.

Do you have any ideas? Thanks!

**Comment by birchera** [comment]
If I understand correctly you don't need to do step 3. Packages can be located in arbitrary structures withing src folder. Not sure what happens if you copy things around. But this could well be the source of the failure.

**Comment by kuoshih** [comment]
I followed your steps and got the same error message.
The steps are as follows:

$mkdir catkin_ws3
$cd catkin_ws3
~/catkin_ws3$ mkdir src
~/catkin_ws3$ cd src
~/catkin_ws3/src$ git clone https://github.com/ethz-asl/nbvplanner.git
~/catkin_ws3/src$ cd nbvplanner
~/catkin_ws3/src/nbvplanner$ git submodule init --
~/catkin_ws3/src/nbvplanner$ git submodule sync --recursive
~/catkin_ws3/src/nbvplanner$ git submodule update --recursive
~/catkin_ws3/src/nbvplanner$ cd ..
~/catkin_ws3/src$ apt-get install ros-<distro>-octomap-*
~/catkin_ws3/src$ apt-get install python-catkin-tools
~/catkin_ws3/src$ catkin build
Then,  I got the same error message.

![error_msg2](https://cloud.githubusercontent.com/assets/26864375/25427677/e4cc2b88-2aa5-11e7-9119-94ed691c5429.jpg)

Thanks!

**Comment by kuoshih** [comment]
Hi @birchera ,

I adopt "catkin_make" instead of "catkin build."
Then, it works. 
Thanks!
