### ISSUE TITLE
nbvPlanner does not work properly in simulation demo

### ISSUE THREAD

**Issue by LjYURAS** [ethz-asl/nbvplanner#22]
Hi,
I am using ubuntu14.04 and ros indigo now. 
I followed the instruction from https://github.com/ethz-asl/nbvplanner/wiki/Installation-Instructions to configured the environment successfully. when i run following command 
roslaunch interface_nbvp_rotors flat_exploration.launch
I get the following errors and the UAV are just drifting in gazebo.
[ERROR] [1542903232.547584120, 0.350000000]: "navigation" passed to lookupTransform argument target_frame does not exist. 
[ERROR] [1542903232.605931369, 0.410000000]: Lookup would require extrapolation at time 0.410000000, but only time 0.510000000 is in the buffer, when looking up transform from frame [world] to frame [navigation]
[ERROR] [1542903249.365794165, 17.050000000]: "world" passed to lookupTransform argument target_frame does not exist. 
Is there any methods I can solve this?

**Comment by LjYURAS** [comment]
I have done nothing, but it works now. I do not know the reason.

**Comment by UsamaMaq** [comment]
Hello i am stuck in same issue... can you think of any way how i can solve it
