### ISSUE TITLE
Planner not set up: Planner not ready!

### ISSUE THREAD

**Issue by reyanshsolis** [ethz-asl/nbvplanner#25]
![Screenshot from 2019-10-03 02-28-24](https://user-images.githubusercontent.com/32535717/66081524-c335ba00-e585-11e9-9879-5a4e6bf52fa2.png)

[ INFO] [1570051382.453454267, 0.050000000]: Physics dynamic reconfigure ready.
[ INFO] [1570051387.420208966, 5.010000000]: Starting the planner: Performing initialization motion
[ INFO] [1570051399.430892708, 17.010000000]: Planning iteration 0
[ERROR] [1570051399.432372840, 17.010000000]: Planner not set up: Planner not ready!

I am using, Ubuntu 18.04, Ros-melodic, Gazebo9.

The package was having a few issue to build in ros-melodic, 
The issue related to rotors_simulator was solved by deleting 
/src/nbvplanner/rotors and cloning in from original repo. rotors_simulation and renaming to rotos, and added the missing files that I found additional in /src/nbvplanner/rotors

I tracked the issue to rotors/rotors_gazebo/launch/spawn_mav.launch
but I am not able to solve it.

Also, some error came related to the \clock, so I used rosparam set /use_sim_time true ,
I also tried rosparam set use_sim_time false,  
but the issue remains unresolved, when I tried to echo the rostopic/firefly/command/..
![image](https://user-images.githubusercontent.com/32535717/66086291-3abd1680-e591-11e9-8ad0-7822b9247180.png)

Related to this error : "Gazebo is Paused" I read somewhere on internet. 
How to unpause it ?

if anyone has faced this issue earlier, kindly help me

**Comment by angelofioretto** [comment]
Add "<plugin name='ros_interface_plugin' filename='librotors_gazebo_ros_interface_plugin.so'/>" in the .world file

**Comment by angelofioretto** [comment]
Add <plugin name='ros_interface_plugin' filename='librotors_gazebo_ros_interface_plugin.so'/> in the .world file

**Comment by angelofioretto** [comment]
Regarding the "Planner not set up: Planner not ready!" error I add  `<plugin` name='ros_interface_plugin' filename='librotors_gazebo_ros_interface_plugin.so'/> in the .world file to resolve it
