### ISSUE TITLE
Exceeding maximum failed iterations, return to previous point!

### ISSUE THREAD

**Issue by Zyhlibrary** [ethz-asl/nbvplanner#32]
When i run the demo (flat_exploration), the planner can initialize, but after initialization, it could not plan and reported "Exceeding maximum failed iterations, return to previous point!" as follows in each iteration. 

[ INFO] [1638969669.122324849, 63.523000000]: Starting the planner: Performing initialization motion
[ INFO] [1638969686.898799717, 75.530000000]: Planning iteration 0
[ INFO] [1638969688.467290489, 76.607000000]: Exceeding maximum failed iterations, return to previous point!
[ INFO] [1638969689.964621217, 77.608000000]: Planning iteration 1
[ INFO] [1638969691.555007969, 78.660000000]: Exceeding maximum failed iterations, return to previous point!
[ INFO] [1638969693.092617836, 79.660000000]: Planning iteration 2
[ INFO] [1638969694.734058334, 80.765000000]: Exceeding maximum failed iterations, return to previous point!

Anyone met the same issue before? Thanks a lot.

**Comment by Mediumcore** [comment]
Hello,I met the same issue when i set resolution from 0.4 to 0.1 :
 [ INFO] [1647413810.627467253, 185.880000000]: Starting the planner: Performing initialization motion
[ INFO] [1647413822.629511693, 197.880000000]: Planning iteration 0
[ INFO] [1647413823.307989306, 198.550000000]: Exceeding maximum failed iterations, return to previous point!
[ INFO] [1647413824.299696295, 199.550000000]: Planning iteration 1
[ INFO] [1647413825.004284673, 200.250000000]: Exceeding maximum failed iterations, return to previous point!

I want to set resolution smaller such as 0.1 ,but the error exceeding maximum failed at the Planning iteration 0. How did you tackle this issue, thanks for help.

**Comment by Zyhlibrary** [comment]
> Hello,I met the same issue when i set resolution from 0.4 to 0.1 : [ INFO] [1647413810.627467253, 185.880000000]: Starting the planner: Performing initialization motion [ INFO] [1647413822.629511693, 197.880000000]: Planning iteration 0 [ INFO] [1647413823.307989306, 198.550000000]: Exceeding maximum failed iterations, return to previous point! [ INFO] [1647413824.299696295, 199.550000000]: Planning iteration 1 [ INFO] [1647413825.004284673, 200.250000000]: Exceeding maximum failed iterations, return to previous point!
> 
> I want to set resolution smaller such as 0.1 ,but the error exceeding maximum failed at the Planning iteration 0. How did you tackle this issue, thanks for help.

Maybe the issue is caused by the map, you can check the process of map building.

**Comment by Mediumcore** [comment]
OK, Thank you very much
