### ISSUE TITLE
[problem] roslaunch interface_nbvp_rotors flat_exploration.launch

### ISSUE THREAD

**Issue by won13y** [ethz-asl/nbvplanner#4]
when I run following commands

    roslaunch interface_nbvp_rotors flat_exploration.launch

it results in following errors

    IOError: [Errno 2] No such file or directory: '/home/wkyoun/catkin_build/src/rotors/rotors_description/urdf/firefly_vi_sensor.gazebo'

So, I tried to find firefly_vi_sensor.gazebo file, but I cannot find.

The full error scripts is as followings:

    wkyoun@wkyoun-15Z960-GA70K:~/catkin_build/src/nbvplanner/interface_nbvp_rotors$ roslaunch interface_nbvp_rotors flat_exploration.launch

    ... logging to /home/wkyoun/.ros/log/c88b0a6a-424e-11e6-a811-1002b5120fb1/roslaunch-wkyoun-15Z960-GA70K-21991.log
    Checking log directory for disk usage. This may take awhile.
    Press Ctrl-C to interrupt
    Done checking log file disk usage. Usage is <1GB.

    Traceback (most recent call last):
      File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
        xacro.main()
      File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 673, in main
        f = open(args[0])
    IOError: [Errno 2] No such file or directory: '/home/wkyoun/catkin_build/src/rotors/rotors_description/urdf/firefly_vi_sensor.gazebo'
    while processing /home/wkyoun/catkin_build/src/nbvplanner/interface_nbvp_rotors/launch/mav_inspector.launch:
    while processing /home/wkyoun/catkin_build/src/rotors/rotors_gazebo/launch/spawn_mav.launch:
    Invalid <param> tag: Cannot load command parameter [robot_description]: command [     /opt/ros    /indigo/share/xacro/xacro.py '/home/wkyoun/catkin_build/src/rotors/rotors_description    /urdf/firefly_vi_sensor.gazebo'     enable_logging:=false     enable_ground_truth:=true     enable_mavlink_interface:=false     log_file:=firefly     mav_name:=firefly] returned with code [1]. 

    Param xml is <param command="     $(find xacro)/xacro.py '$(arg model)'         enable_logging:=$(arg enable_logging)     enable_ground_truth:=$(arg enable_ground_truth)         enable_mavlink_interface:=$(arg enable_mavlink_interface)     log_file:=$(arg log_file)         mav_name:=$(arg mav_name)" name="robot_description"/>
    The traceback for the exception was written to the log file

**Comment by Zeta611** [comment]
The current master branch does not seem to have firefly_vi_sensor.gazebo file..

**Comment by birchera** [comment]
Thank you for pointing out. I am working on a solution that will solve this divergence problem and also prevent similar ones in the future.

**Comment by won13y** [comment]
@birchera Thank you for the reply. I am really looking forward to run your nbvp ROS example ASAP.

**Comment by Zeta611** [comment]
@won13y For now, simply use the version of rotors_simulator before April 4th. [``](https://github.com/ethz-asl/rotors_simulator/tree/4f763acdec2225809b9937adca0740730d53ddc1) worked for my case.

**Comment by won13y** [comment]
@Zeta611 

Thank you for the reply. I would really appreciate.

I tried to run the the version of rotors_simulator before April 4th, but

https://github.com/ethz-asl/rotors_simulator/tree/4f763acdec2225809b9937adca0740730d53ddc1 

The problem occured

In order to run the following sections

    Basic Usage

    Launch the simulator with a hex-rotor helicopter model, in our case, the AscTec Firefly.
    
    $ roslaunch rotors_gazebo mav_empty_world.launch mav_name:=firefly

it does not include mav_empty_world.launch in launch folder of rotors_gazebo  

**mav_empty_world.launch** 

Would you please let me know how to run the nbvplanner example?

I was able to run successfully RotorS Gazebo Simulator,

but what I really want to run is the nbvplanner as described in following paper

    Receding Horizon "Next-Best-View" Planner for 3D Exploration

Thank you in advance!

**Comment by Zeta611** [comment]
mav_empty_world.launch
does not exist in this version, yet I could run the nbvplanner, but 
    roslaunch interface_nbvp_rotors flat_exploration.launch
should be executed fine. Have you tried rebuilding your catkin workspace? Make sure to build it in release mode via:
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

**Comment by won13y** [comment]
@Zeta611 Thank you very much

I tried to execute the the version of rotors_simulator before April 4th, 

https://github.com/ethz-asl/rotors_simulator/tree/4f763acdec2225809b9937adca0740730d53ddc1 

    roslaunch interface_nbvp_rotors flat_exploration.launch

It finally works! Thank you!

I hope that Master branch is also available for me to execute nbvp planner ASAP!

I really appreciate your help!

**Comment by Zeta611** [comment]
@won13y, I’m happy to hear that it works! :D

**Comment by birchera** [comment]
I am glad to hear you found a solution in the meantime. #5 should now do the trick.

Thanks for reporting!
