### ISSUE TITLE
Rechek the source code in rrt.cpp 

### ISSUE THREAD

**Issue by SoohwanSong** [ethz-asl/nbvplanner#6]
Would you check the source code line #547 in rrt.cpp?

I think that the code should be changed like this: 

#547  if (inFoV) {   --------->  if (!inFoV) { 

Thank you.

**Comment by birchera** [comment]
Good catch, thanks a lot for reporting!

Should be fixed in https://github.com/ethz-asl/nbvplanner/pull/7.
