### ISSUE TITLE
rtt.cpp: Possible errors in computation of visibility inside gain

### ISSUE THREAD

**Issue by johuber** [ethz-asl/nbvplanner#9]
Hi, I used the visibility computation from the gain() function in rrt.cpp and found two issues:

1. in rrt.cpp, line 529
`if(dir.norm()>rangeSq)`
The function norm() computes the actual norm, not the square of it. Hence shouldn't this be changed to:
`if(dir.transpose().dot(dir)>rangeSq)`

2. in rrt.cpp, line 547:
`if(!inFoV)`
Don't we want to break this loop, when a point is INSIDE the field of view. Hence this should be:
`if(inFOV)`
Otherwise only points OUTSIDE the FoV will be used for the computation of the gain, which does not make sense.

I used this code to compute the visibility within my own work, and it did only give the proper results after I made those two changes.

I just noticed that the 2nd point was changed due to the closed issue #6 . However, after this change the computation is wrong, the way it was done before was correct.

**Comment by birchera** [comment]
Hi @johuber, both of your points make sense. I am going to take a closer look asap.
